baseURL = "https://metonimie.github.io/hugo-inception"
languageCode = "en-us"
title = "Inception"
publishDir = "docs"

[params]
    description = "Internet of Things Meets Complex Networks for Early Prediction and Management of Chronic Obstructive Pulmonary Disease"